# Generated by Django 4.2.5 on 2023-09-13 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "first_course",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("main_course", models.CharField(max_length=255)),
                ("drink", models.CharField(blank=True, max_length=255, null=True)),
                ("dessert", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("lunch_date", models.DateTimeField()),
                (
                    "vote_status",
                    models.CharField(
                        choices=[("opened", "Opened"), ("closed", "Closed")],
                        default="opened",
                        max_length=255,
                    ),
                ),
                ("is_winner", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.menu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("info", models.TextField(blank=True, null=True)),
                (
                    "representative",
                    models.ManyToManyField(
                        related_name="restaurant_reps", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restaurants",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="votes",
            field=models.ManyToManyField(
                related_name="liked_posts",
                through="restaurant.Vote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
