# Generated by Django 4.2.5 on 2023-09-13 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="representative",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="restaurant_reps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
