# Generated by Django 4.2.5 on 2023-09-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_alter_restaurant_representative"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="lunch_date",
            field=models.DateField(),
        ),
    ]
