# Generated by Django 4.2.5 on 2023-09-13 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("first_name", "last_name")},
        ),
    ]
